### PR TITLE
[DPP-388] Updates documentation to reflect unification.

### PR DESCRIPTION
**Pull request by jgrahamthomas**
**http://docs.gusto.com/v1/benefits Before**
screen shot 2017-10-26 at 5 09 15 pm

**http://docs.gusto.com/v1/benefits After**
screen shot 2017-10-26 at 5 09 25 pm

### CODE REVIEW

**Comment by kendralyndon-gusto** [comment]
Looks good except for a small typo. I also noticed there's no mention of HSA - are partners able to set up HSA's through our API?

**Comment by jgrahamthomas** [comment]
@kendralyndon-gusto Yes, they can setup HSA, but they've never been able to setup taxable HSA (until we created it). So I think it's ok not to mention.

**Comment by kendralyndon-gusto** [comment]
sounds good. @zp-alfred accept

**Comment by zp-alfred** [comment]
Accepted by kendralyndon-gusto!

**Pull request merged**
